# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: source env.sh # runs during prebuild
    command: source env.sh

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
vscode:
  extensions:
    - johnpapa.winteriscoming
# ms-vscode.cpptools
    - ms-vscode.cpptools-themes
#    - austin.code-gnu-global
# ommited can be installed with script